### ISSUE TITLE
Cannot edit existing messages while waiting in the queue

### ISSUE THREAD

**Issue by NintendoManiac64** [kaihordewebui/kaihordewebui.github.io#4]
When I last tried it (2023-03-25), we were still able to edit existing messages while we waited in the queue.

As of today (2023-03-30) I noticed that this is not possible.

**Comment by LostRuins** [comment]
That is correct. Edit mode is now disabled while waiting for a response, because there was a risk that it would corrupt the story if a response was received while the user was halfway editing a message, since it automatically merges the text when the focus leaves the edit box, and receiving a message response also modifies the story. It's also counterintuitive, because although you "edit" the message while waiting, none of the edits will get sent to the Horde worker (which is already processing the original text). So the text you see and the "real" context will become different and that is not something you want.

**Comment by NintendoManiac64** [comment]
> although you "edit" the message while waiting, none of the edits will get sent to the Horde worker (which is already processing the original text)

Is this the case even when it's doing the numerical countdown and has not yet reached the green-colored spinner?

**Comment by LostRuins** [comment]
> > although you "edit" the message while waiting, none of the edits will get sent to the Horde worker (which is already processing the original text)
> 
> Is this the case even when it's doing the numerical countdown and has not yet reached the green-colored spinner?

Yes, the instant you click "Submit" the text is sent to the horde and cannot be modified already. So locally editing past that point should be prevented.

**Comment by NintendoManiac64** [comment]
Ah, understood. I'll close this them.
